// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: history.sql

package db

import (
	"context"
)

const getBotState = `-- name: GetBotState :one
SELECT value FROM bot_state WHERE key = $1
`

func (q *Queries) GetBotState(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, getBotState, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const upsertBotState = `-- name: UpsertBotState :exec
INSERT INTO bot_state (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW()
`

type UpsertBotStateParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertBotState(ctx context.Context, arg UpsertBotStateParams) error {
	_, err := q.db.Exec(ctx, upsertBotState, arg.Key, arg.Value)
	return err
}
