// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type BotState struct {
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Exercise struct {
	ID        int32     `json:"id"`
	RoutineID int32     `json:"routine_id"`
	Name      string    `json:"name"`
	Position  int32     `json:"position"`
	Sets      int32     `json:"sets"`
	RepsMin   int32     `json:"reps_min"`
	RepsMax   int32     `json:"reps_max"`
	Notes     string    `json:"notes"`
	CreatedAt time.Time `json:"created_at"`
}

type Routine struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Session struct {
	ID          int32     `json:"id"`
	RoutineName string    `json:"routine_name"`
	StartedAt   time.Time `json:"started_at"`
}

type SessionSet struct {
	ID           int32       `json:"id"`
	SessionID    int32       `json:"session_id"`
	ExerciseName string      `json:"exercise_name"`
	SetNumber    int32       `json:"set_number"`
	Reps         int32       `json:"reps"`
	WeightKg     float64     `json:"weight_kg"`
	Rpe          pgtype.Int4 `json:"rpe"`
	LoggedAt     time.Time   `json:"logged_at"`
}
