// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: routines.sql

package db

import (
	"context"
)

const deleteExercisesByRoutine = `-- name: DeleteExercisesByRoutine :exec
DELETE FROM exercises WHERE routine_id = $1
`

func (q *Queries) DeleteExercisesByRoutine(ctx context.Context, routineID int32) error {
	_, err := q.db.Exec(ctx, deleteExercisesByRoutine, routineID)
	return err
}

const getExercisesByRoutine = `-- name: GetExercisesByRoutine :many
SELECT e.id, e.routine_id, e.name, e.position, e.sets, e.reps_min, e.reps_max, e.notes, e.created_at
FROM exercises e
JOIN routines r ON r.id = e.routine_id
WHERE r.name = $1
ORDER BY e.position
`

func (q *Queries) GetExercisesByRoutine(ctx context.Context, name string) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, getExercisesByRoutine, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.RoutineID,
			&i.Name,
			&i.Position,
			&i.Sets,
			&i.RepsMin,
			&i.RepsMax,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoutineByName = `-- name: GetRoutineByName :one
SELECT id, name, created_at, updated_at FROM routines WHERE name = $1
`

func (q *Queries) GetRoutineByName(ctx context.Context, name string) (Routine, error) {
	row := q.db.QueryRow(ctx, getRoutineByName, name)
	var i Routine
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertExercise = `-- name: InsertExercise :one
INSERT INTO exercises (routine_id, name, position, sets, reps_min, reps_max, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, routine_id, name, position, sets, reps_min, reps_max, notes, created_at
`

type InsertExerciseParams struct {
	RoutineID int32  `json:"routine_id"`
	Name      string `json:"name"`
	Position  int32  `json:"position"`
	Sets      int32  `json:"sets"`
	RepsMin   int32  `json:"reps_min"`
	RepsMax   int32  `json:"reps_max"`
	Notes     string `json:"notes"`
}

func (q *Queries) InsertExercise(ctx context.Context, arg InsertExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, insertExercise,
		arg.RoutineID,
		arg.Name,
		arg.Position,
		arg.Sets,
		arg.RepsMin,
		arg.RepsMax,
		arg.Notes,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.RoutineID,
		&i.Name,
		&i.Position,
		&i.Sets,
		&i.RepsMin,
		&i.RepsMax,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const upsertRoutine = `-- name: UpsertRoutine :one
INSERT INTO routines (name)
VALUES ($1)
ON CONFLICT (name) DO UPDATE SET updated_at = NOW()
RETURNING id, name, created_at, updated_at
`

func (q *Queries) UpsertRoutine(ctx context.Context, name string) (Routine, error) {
	row := q.db.QueryRow(ctx, upsertRoutine, name)
	var i Routine
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
