// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (routine_name)
VALUES ($1)
RETURNING id, routine_name, started_at
`

func (q *Queries) CreateSession(ctx context.Context, routineName string) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, routineName)
	var i Session
	err := row.Scan(&i.ID, &i.RoutineName, &i.StartedAt)
	return i, err
}

const getExerciseHistory = `-- name: GetExerciseHistory :many
SELECT
    ss.id,
    ss.exercise_name,
    ss.set_number,
    ss.reps,
    ss.weight_kg,
    ss.rpe,
    ss.logged_at,
    s.started_at AS session_date
FROM session_sets ss
JOIN sessions s ON s.id = ss.session_id
WHERE ss.exercise_name ILIKE $1
ORDER BY ss.logged_at DESC
LIMIT $2
`

type GetExerciseHistoryParams struct {
	ExerciseName string `json:"exercise_name"`
	Limit        int32  `json:"limit"`
}

type GetExerciseHistoryRow struct {
	ID           int32       `json:"id"`
	ExerciseName string      `json:"exercise_name"`
	SetNumber    int32       `json:"set_number"`
	Reps         int32       `json:"reps"`
	WeightKg     float64     `json:"weight_kg"`
	Rpe          pgtype.Int4 `json:"rpe"`
	LoggedAt     time.Time   `json:"logged_at"`
	SessionDate  time.Time   `json:"session_date"`
}

func (q *Queries) GetExerciseHistory(ctx context.Context, arg GetExerciseHistoryParams) ([]GetExerciseHistoryRow, error) {
	rows, err := q.db.Query(ctx, getExerciseHistory, arg.ExerciseName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExerciseHistoryRow
	for rows.Next() {
		var i GetExerciseHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseName,
			&i.SetNumber,
			&i.Reps,
			&i.WeightKg,
			&i.Rpe,
			&i.LoggedAt,
			&i.SessionDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastSessionByRoutine = `-- name: GetLastSessionByRoutine :one
SELECT id, routine_name, started_at FROM sessions
WHERE routine_name = $1
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetLastSessionByRoutine(ctx context.Context, routineName string) (Session, error) {
	row := q.db.QueryRow(ctx, getLastSessionByRoutine, routineName)
	var i Session
	err := row.Scan(&i.ID, &i.RoutineName, &i.StartedAt)
	return i, err
}

const getSessionSetsBySession = `-- name: GetSessionSetsBySession :many
SELECT id, session_id, exercise_name, set_number, reps, weight_kg, rpe, logged_at FROM session_sets
WHERE session_id = $1
ORDER BY exercise_name, set_number
`

func (q *Queries) GetSessionSetsBySession(ctx context.Context, sessionID int32) ([]SessionSet, error) {
	rows, err := q.db.Query(ctx, getSessionSetsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionSet
	for rows.Next() {
		var i SessionSet
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ExerciseName,
			&i.SetNumber,
			&i.Reps,
			&i.WeightKg,
			&i.Rpe,
			&i.LoggedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodaySession = `-- name: GetTodaySession :one
SELECT id, routine_name, started_at FROM sessions
WHERE routine_name = $1
AND DATE(started_at) = CURRENT_DATE
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetTodaySession(ctx context.Context, routineName string) (Session, error) {
	row := q.db.QueryRow(ctx, getTodaySession, routineName)
	var i Session
	err := row.Scan(&i.ID, &i.RoutineName, &i.StartedAt)
	return i, err
}

const insertSessionSet = `-- name: InsertSessionSet :one
INSERT INTO session_sets (session_id, exercise_name, set_number, reps, weight_kg, rpe)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, session_id, exercise_name, set_number, reps, weight_kg, rpe, logged_at
`

type InsertSessionSetParams struct {
	SessionID    int32       `json:"session_id"`
	ExerciseName string      `json:"exercise_name"`
	SetNumber    int32       `json:"set_number"`
	Reps         int32       `json:"reps"`
	WeightKg     float64     `json:"weight_kg"`
	Rpe          pgtype.Int4 `json:"rpe"`
}

func (q *Queries) InsertSessionSet(ctx context.Context, arg InsertSessionSetParams) (SessionSet, error) {
	row := q.db.QueryRow(ctx, insertSessionSet,
		arg.SessionID,
		arg.ExerciseName,
		arg.SetNumber,
		arg.Reps,
		arg.WeightKg,
		arg.Rpe,
	)
	var i SessionSet
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ExerciseName,
		&i.SetNumber,
		&i.Reps,
		&i.WeightKg,
		&i.Rpe,
		&i.LoggedAt,
	)
	return i, err
}
